### ISSUE TITLE
replace hard coded strings with constants

### ISSUE THREAD

**Issue by bogdanrn** [talentivan/tarbarnapp#12]
We should not use hardcoded strings in app settings, this only leaves room for minor mistakes that will have major impacts long term. 

I added an example of using constants to replace the animated titles show_options, same consant files are imported and used both in themeApp and adminApp. This will help us to never make a mistake and the compiler will alert us if we try to use some undefined values. 

You should replace all hardcoded strings and create constants for them in that common folder.

**Comment by talentivan** [comment]
Fixed
