### ISSUE TITLE
remove ids from elements

### ISSUE THREAD

**Issue by bogdanrn** [talentivan/tarbarnapp#3]
use only classss, no ids. If you bind a javascript function to an element, use a class that starts with `js-`. For example you have `<button id="btnDuplicate" class="action-button secondary icon-duplicate" data-hover="Duplicate"></button>`.

It should be

`<button class="action-button secondary icon-duplicate js-btnDuplicate" data-hover="Duplicate"></button>
`

Never bind css to classes that start with `js-`, never bind js to classes that don't start with `js-` or have css already on them. This will help us long term greatly

**Comment by talentivan** [comment]
I removed all ids from elements and jquery selectors use class name as you recommended.
