### ISSUE TITLE
collection methods

### ISSUE THREAD

**Issue by bogdanrn** [talentivan/tarbarnapp#7]
split the `settings_methods.js` file into multple files like this: 
Create a new folder for each collection, inside those, make a js file for each method.  The structure should look like this 

```
/imports/api/dbmanager/AnimatedSettings/AnimatedSettings.js`
/imports/api/dbmanager/AnimatedSettings/methods/delete.js`
``` 
etc.

**Comment by talentivan** [comment]
done
